// Generated by config/domains/generate-onboarding-config.mjs. Do not edit manually.
(function configureSurplasseDomains() {
  const profiles = Object.freeze({
  "development": {
    "APP_SCHEME": "https",
    "APP_BASE_DOMAIN": "surplasse.test",
    "APP_BASE_URL": "https://surplasse.test",
    "ONBOARDING_URL": "https://surplasse.test",
    "DASHBOARD_URL": "https://dashboard.surplasse.test",
    "API_URL": "https://api.surplasse.test",
    "LOCAL_CONTROL_URL": "https://local.surplasse.test",
    "DOCS_URL": "https://docs.surplasse.test",
    "MAILPIT_URL": "https://mail.surplasse.test",
    "COOKIE_DOMAIN": "",
    "RESERVED_SUBDOMAINS": "www,api,dashboard,docs,app,admin,local,mail"
  },
  "production": {
    "APP_SCHEME": "https",
    "APP_BASE_DOMAIN": "surplasse.com",
    "APP_BASE_URL": "https://surplasse.com",
    "ONBOARDING_URL": "https://surplasse.com",
    "DASHBOARD_URL": "https://dashboard.surplasse.com",
    "API_URL": "https://api.surplasse.com",
    "LOCAL_CONTROL_URL": "",
    "DOCS_URL": "https://docs.surplasse.com",
    "MAILPIT_URL": "",
    "COOKIE_DOMAIN": "",
    "RESERVED_SUBDOMAINS": "www,api,dashboard,docs,app,admin,local,mail"
  }
});
  const hostname = window.location.hostname.toLowerCase().replace(/\.$/u, "");
  const developmentDomain = profiles.development.APP_BASE_DOMAIN;
  const loopbackHosts = new Set(["localhost", "127.0.0.1", "::1", "[::1]"]);
  const isDevelopment =
    loopbackHosts.has(hostname) ||
    hostname === developmentDomain ||
    hostname.endsWith(`.${developmentDomain}`);
  const selectedProfile = isDevelopment ? "development" : "production";

  window.SURPLASSE_DOMAIN_CONFIG = Object.freeze(
    { ...profiles[selectedProfile], PROFILE: selectedProfile },
  );
})();
